base_url = "https://schilk.co"
compile_sass = false
build_search_index = false
author = "Philipp Schilk"
exclude_paginated_pages_in_sitemap = "all"

taxonomies = [{ name = "tags", paginate_by = 8, feed = true }]
taxonomy_root = "blog"

[markdown]
render_emoji = true
# Enable github-style `note`, `tip`, `important`, `warning`, or `caution`
# callouts.
github_alerts = true

[markdown.highlighting]
theme = "github-light"
error_on_missing_language = true
extra_grammars = ["syntax/psASM.json"]

[extra]
